version: "3"

services:
  omeka-web:
    build:
      context: .
      args:
        OMEKA_S_VERSION : "4.0.4"
        PHP_VERSION : 8.1
    restart: "no"
    env_file: ".env"
    
    ports:
      - 8080:80
    volumes:
      - ./files:/var/www/omeka-s/files
      - ./logs:/var/www/omeka-s/logs
      - ./modules:/var/www/omeka-s/modules
      - ./themes:/var/www/omeka-s/themes   
    depends_on:
      - omeka-db

  omeka-db:
    image: mariadb:10.6
    restart: "no"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  omeka-db-admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "no"
    ports:
      - 8081:80
    environment:
      - PMA_HOST=omeka-db
    depends_on:
      - omeka-db